### ISSUE TITLE
How to use listener version

### ISSUE THREAD

**Issue by mikeerickson** [nunomaduro/collision#102] opened 2020-03-26 02:41 UTC
I used to use our own result-printer alongside listener for uber beautiful output.

However, just updated to Laravel 7 and the listener no longer works?  

Is there still a way to use the Collision listener and not as printerClass?

**Comment by nunomaduro** [comment] 2020-03-26 09:11
You just want the error output with your own result-printer?

**Comment by mikeerickson** [comment] 2020-03-26 23:14
Yes, that is correct. When it was a listener option the output combined with our printer, it looked better

**Comment by johanvanhelden** [comment] 2020-04-28 15:19
I would also prefer an error-only listener.

**Comment by nunomaduro** [comment] 2020-05-11 13:48
Duplicate of https://github.com/nunomaduro/collision/issues/99

**Closed as completed by nunomaduro** 2020-05-11 13:48 UTC
Labels: enhancement, question

**Comment by mikeerickson** [comment] 2020-07-04 15:46
@nunomaduro Have you considered adding this?
